'use client'
import Head from 'next/head';
import styles from '../../style';
import Navbar from '@components/Header/Navbar';

import { SyntheticEvent, useState } from 'react';
import axios from 'axios';
import Link from 'next/link';
import { useRouter } from 'next/router';
export default function Home() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [userType, setUserType] = useState('');

  const handleSubmit = async (event: SyntheticEvent) => {
    event.preventDefault();
    await axios
    .post('http://127.0.0.1:8000/auth/login/', {
      email: email,
      password: password,
    })
    .then(response => {
      const refresh_token = response.data.refresh;
      const access_token = response.data.access;
      console.log('refresh', refresh_token);
      console.log('access', access_token);
      localStorage.setItem('refres_token', refresh_token);
      localStorage.setItem('access_token', access_token);
    });

    await router.push('/login');
  };
  return (
    <>
      <Head>
        <title>Úles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-primary h-screen w-full overflow-hidden">
        <div className={`${styles.paddingX} ${styles.flexCenter}`}>
          <div className={`${styles.boxWidth}`}>
            <Navbar></Navbar>
          </div>
        </div>
        <div className={`${styles.flexStart}`}>
          <div className={`${styles.boxWidth}`}>
            <div className="flex flex-col items-center justify-center px-6 py-8 mx-auto lg:py-0">
              <div className="w-full bg-white rounded-lg shadow md:mt-0 sm:max-w-md xl:p-0">
                <div className="p-6 space-y-4 md:space-y-6 sm:p-8">
                  <h2 className="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl text-center">
                    Создать аккаунт
                  </h2>
                  <form
                    className="space-y-4 md:space-y-6"
                    action="#"
                    onSubmit={handleSubmit}>
                    <div>
                      <label
                        htmlFor="email"
                        className="block mb-2 text-sm font-medium text-gray-900">
                        Ваша эл-почта
                      </label>
                      <input
                        type="email"
                        name="email"
                        id="email"
                        value={email}
                        onChange={e => setEmail(e.target.value)}
                        className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5"
                        placeholder="name@email.com"
                      />
                    </div>
                    <div>
                      <label
                        htmlFor="roles"
                        className="block mb-2 text-sm font-medium text-gray-900">
                        Выберите вашу роль
                      </label>
                      <select
                        id="roles"
                        value={userType}
                        onChange={e => setUserType(e.target.value)}
                        className="bg-gray-50 border  border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                        <option value="1">Волонтер</option>
                        <option value="2">Магазин</option>
                        <option value="3">Получатель</option>
                      </select>
                    </div>
                    <div>
                      <label
                        htmlFor="password"
                        className="block mb-2 text-sm font-medium text-gray-900">
                        Пароль
                      </label>
                      <input
                        type="password"
                        name="password"
                        id="password"
                        placeholder="••••••••"
                        value={password}
                        onChange={e => setPassword(e.target.value)}
                        className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5"
                      />
                    </div>

                    <button
                      type="submit"
                      className="w-full text-white bg-gray-600 
                      hover:bg-primary-700 focus:ring-4 focus:outline-none 
                      focus:ring-primary-300 font-medium rounded-lg 
                      text-sm px-5 py-2.5 
                      text-center">
                      Создать аккаунт
                    </button>
                    <p className="text-sm font-light text-gray-500">
                      Уже есть аккаунт?{' '}
                      <Link
                        href="/login"
                        className="font-medium text-primary-600 hover:underline">
                        Войти
                      </Link>
                    </p>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
